dia = float(input("Diga um numero"))

def dias(dia):
    if dia == 1:
        print("O dia será domingo")
    elif dia == 2:
        print("O dia será segunda")
    elif dia == 3:
        print("O dia será terça")
    elif dia == 4:
        print("O dia será quarta")
    elif dia == 5:
        print("O dia será quinta")
    elif dia == 6:
        print("O dia será sexta")
    elif dia == 7:
        print("O dia será sabado")
dias(dia)
          
    
    
    